# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Technology, CS and Random Thoughts
tagline:          Mario Kosmiskas
url:              http://mariokmk.github.io
paginate:         1
baseurl:          /
author:
  name:           Mario Kosmiskas
  url:            https://twitter.com/mariokmk
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/mariokmk/mariokmk.github.io

# Header
pages_list:
  Archive: '/archive'
  Feed: '/atom.xml'
